# Generated by Django 4.2.30 on 2026-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('published_date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('strong_phobic', models.IntegerField(default=0)),
                ('medium_phobic', models.IntegerField(default=0)),
                ('weak_phobic', models.IntegerField(default=0)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('detection_payload', models.JSONField(blank=True, null=True)),
                ('storage_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detection',
                'verbose_name_plural': 'Detections',
                'db_table': 'detections',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField()),
                ('storage_path', models.TextField()),
                ('bucket', models.TextField()),
                ('filename', models.TextField()),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Internal Document',
                'verbose_name_plural': 'Internal Documents',
                'db_table': 'internal_documents',
                'ordering': ['-uploaded_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('key', models.TextField(unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Pipeline Config',
                'db_table': 'pipeline_config',
                'ordering': ['key'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('level', models.CharField(max_length=20)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'db_table': 'pipeline_logs',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('current_step', models.IntegerField(default=0)),
                ('step1_articles', models.IntegerField(default=0)),
                ('step2_detections', models.IntegerField(default=0)),
                ('step3_reports', models.IntegerField(default=0)),
                ('failed_step', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('config_snapshot', models.JSONField(blank=True, null=True)),
                ('storage_prefix', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pipeline Run',
                'verbose_name_plural': 'Pipeline Runs',
                'db_table': 'pipeline_runs',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('executive_summary', models.TextField(blank=True, null=True)),
                ('qualitative_insight', models.TextField(blank=True, null=True)),
                ('refs_count', models.IntegerField(default=0)),
                ('report_payload', models.JSONField(blank=True, null=True)),
                ('storage_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('title', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('site', models.TextField(blank=True, null=True)),
                ('published_date', models.TextField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('search_term', models.TextField(blank=True, null=True)),
                ('date_range', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('scrape_status', models.TextField(blank=True, null=True)),
                ('scrape_method', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('storage_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scraped Article',
                'verbose_name_plural': 'Scraped Articles',
                'db_table': 'scraped_articles',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
